### ISSUE TITLE
LinearWarmupCosineAnnealingLR import issue

### ISSUE THREAD

**Issue by JessieJiang1011** [Flash-321/ARLDM#28]
```
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    from pl_bolts.optimizers.lr_scheduler import LinearWarmupCosineAnnealingLR
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/__init__.py", line 11, in <module>
    from pl_bolts import (  # noqa: E402
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/callbacks/__init__.py", line 6, in <module>
    from pl_bolts.callbacks.ssl_online import SSLOnlineEvaluator
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/callbacks/ssl_online.py", line 12, in <module>
    from pl_bolts.models.self_supervised.evaluator import SSLEvaluator
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/models/self_supervised/__init__.py", line 21, in <module>
    from pl_bolts.models.self_supervised.cpc.cpc_module import CPC_v2
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/models/self_supervised/cpc/__init__.py", line 1, in <module>
    from pl_bolts.models.self_supervised.cpc.cpc_module import CPC_v2
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/models/self_supervised/cpc/cpc_module.py", line 14, in <module>
    from pl_bolts.datamodules.stl10_datamodule import STL10DataModule
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/datamodules/__init__.py", line 1, in <module>
    from pl_bolts.datamodules.async_dataloader import AsynchronousLoader
  File "/anaconda3/envs/arldm2/lib/python3.8/site-packages/pl_bolts/datamodules/async_dataloader.py", line 9, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'
```

**Comment by JessieJiang1011** [comment]
I'm strictly following the process in readme, but I think there's some version conflict issue.

**Comment by S-Manasa** [comment]
@JessieJiang1011 Same, I'm also getting the same error. Please tell if you have resolved it and if yes, how?

**Comment by janak11111** [comment]
@JessieJiang1011 @S-Manasa  I am also facing the same issue. 

I resolve this by below

1) comment that import statement (from torch._six import string_classes)
2) replace string_classes with "str" in the same file.
